name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.set_env.outputs.image_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Image Name
        id: set_env
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          IMAGE_NAME=$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT          

  get-and-set-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.set_new_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Last Tag Version
        id: get_last_tag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "Last tag version: $LAST_TAG"
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV

      - name: Get Convetional commit
        uses: webiny/action-conventional-commits@v1.1.0
        id: cc
        with:
          allowed-commit-types: "feat,fix"

      - name: Set New Version
        id: set_new_version
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "Last tag version: $LAST_TAG"

          COMMITS=$(git log $LAST_TAG..HEAD --oneline)
          MAJOR=0
          MINOR=0
          PATCH=0

          for COMMIT in $COMMITS; do
            if [[ $COMMIT == *"feat:"* ]]; then
              MINOR=$((MINOR+1))
            elif [[ $COMMIT == *"fix:"* ]]; then
              PATCH=$((PATCH+1))
            fi
          done

          IFS='.' read -ra ADDR <<< "$LAST_TAG"

          if [ $MAJOR -ne 0 ]; then
            NEW_VERSION="$((ADDR[0]+1)).0.0"
          elif [ $MINOR -ne 0 ]; then
            NEW_VERSION="${ADDR[0]}.$((ADDR[1]+1)).0"
          elif [ $PATCH -ne 0 ]; then
            NEW_VERSION="${ADDR[0]}.${ADDR[1]}.$((ADDR[2]+1))"
          else
            NEW_VERSION="$LAST_TAG"
          fi

          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

  linter:
    runs-on: ubuntu-latest
    needs: get-and-set-version
    steps:
      - uses: actions/checkout@v3
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile

  build-and-publish:
    runs-on: ubuntu-latest
    needs: [get-and-set-version, linter, prepare]
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ${{ needs.prepare.outputs.image_name }}:${{ needs.get-and-set-version.outputs.new_version }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ needs.prepare.outputs.image_name }}:${{ needs.get-and-set-version.outputs.new_version }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL'

      - name: Push to Docker Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag ${{ needs.prepare.outputs.image_name }}:${{ needs.get-and-set-version.outputs.new_version }} xavimf87/${{ needs.prepare.outputs.image_name }}:${{ needs.get-and-set-version.outputs.new_version }}
          docker push xavimf87/${{ needs.prepare.outputs.image_name }}:${{ needs.get-and-set-version.outputs.new_version }}

  create-tag-and-release:
    needs: [get-and-set-version, build-and-publish]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Set up Git Config
        env:
          CI_USER: ${{ secrets.CI_USER }}
          CI_EMAIL: ${{ secrets.CI_EMAIL }}
        run: |
          git config --global user.name "$CI_USER"
          git config --global user.email "$CI_EMAIL"
  
      - name: Generate Changelog
        id: changelog
        uses: charmixer/auto-changelog-action@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_branch: main
          future_release: ${{ needs.get-and-set-version.outputs.new_version }}
  
      - name: Commit Changelog
        run: |
          git add CHANGELOG.md
          git commit -m "Update Changelog"
          git push
  
      - name: Create and Push Tag
        run: |
          VERSION=${{ needs.get-and-set-version.outputs.new_version }}
          git tag $VERSION
          git push origin $VERSION
  
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: CHANGELOG.md
          title: Release ${{ needs.get-and-set-version.outputs.new_version }}
          tag_name: ${{ needs.get-and-set-version.outputs.new_version }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
